#!/usr/bin/env node
/**
 * Generate src/app/tokens.generated.css from the canonical design-tokens.json.
 * Emits CSS custom properties for the brand + flavor + mascot colors so the
 * web theme stays in lockstep with mobile (which generates a Dart file from
 * the same source). Run with `npm run gen:tokens`. Do not hand-edit the output.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "design-tokens.json"), "utf8"));

const lines = [];
lines.push("/* GENERATED by scripts/gen-tokens.mjs from design-tokens.json — do not edit. */");
lines.push(":root {");
lines.push(`  --brand-primary: ${tokens.brand.primary.hsl};`);
lines.push(`  --brand-accent: ${tokens.brand.accent.hsl};`);
for (const [k, v] of Object.entries(tokens.mascot)) {
  if (k.startsWith("$")) continue;
  lines.push(`  --pip-${k}: ${v};`);
}
lines.push("}");
lines.push(".dark {");
lines.push(`  --brand-primary: ${tokens.brand.primaryDark.hsl};`);
lines.push("}");
for (const [name, f] of Object.entries(tokens.flavors)) {
  lines.push(`[data-flavor="${name}"] {`);
  lines.push(`  --brand-primary: ${f.primary.hsl};`);
  lines.push(`  --brand-accent: ${f.accent.hsl};`);
  lines.push("}");
}
lines.push("");

const out = resolve(root, "src/app/tokens.generated.css");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} (${Object.keys(tokens.flavors).length} flavors, ${Object.keys(tokens.mascot).filter((k) => !k.startsWith("$")).length} mascot colors)`);
